### PR TITLE
Double quote build args to support complex values

### LINKED ISSUE #79: Multiline Build Arguments Break Docker Build/Put
We frequently inject ssh-keys into containers at build time (such as to allow rubygems or npm access to private git repos during build) using `--build-args`. When attempting to do this in Concourse, two different error conditions appear.

      - put: docker
        params:
          build: master
          tag: version/version
          build_args:
            KEY: {{ssh-key}}

Results in the following error:

    bad flag syntax: -----END

Using | notation to denote multiline results in slightly different behavior.

      - put: docker
        params:
          build: master
          tag: version/version
          build_args:
            KEY: |
              {{ssh-key}}

Error:

    "docker build" requires exactly 1 argument(s).
    See 'docker build --help'.

    Usage:  docker build [OPTIONS] PATH | URL | -

    Build an image from a Dockerfile

### LINKED ISSUE #158: Multivalue build_args does not work.
Passing build args with spaces in it does not work at. 
```
build_args:
  PHP_BUILD_ARGS: --enable-fpm --enable-cli
```
will result in: 
```
waiting for docker to come up...
Login Succeeded
unknown flag: --enable-cli
See 'docker build --help'.
```

Wrap the values in quotes in the Pipeline.yml does not work due to there are removed on `set-pipeline`

I suggest to wrap the whole build-arg in qoutes in `assets/out` lines 116 and 120, so the target output will be `--build-arg "PHP_BUILD_ARGS=--enable-fpm --enable-cli"`

### PR DESCRIPTION
**Pull request by jfmyers9**
This change properly escapes multiline/complex build arg values when calling `docker build`.

Fixes #158, Fixes #79 

*Note*: We couldn't get the tests to run on OSX. We think the `README.md` needs some updating?

Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jfmyers9 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=159)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=159) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@jfmyers9 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/docker-image-resource&pullRequestId=159)!

**Comment by jfmyers9** [comment]
We believe this change may fix the above issues. As said we struggled to run the `out` tests when running `docker build`. The intention of this PR is to hopefully drive the conversation forward on the linked issues.

**Comment by ljfranklin** [comment]
Don't merge this, it doesn't work :) Fixing it now...

**Comment by ljfranklin** [comment]
Updated, should be working now. This is the simplest solution we could find which correctly quoted the values of build args.

**Comment by vito** [comment]
Sorry, the build has been failing for a bit and we hadn't noticed. It should be fixed now; I re-ran the build and it's green.

**Comment by jfmyers9** [comment]
@vito This was somewhat difficult to test due to nature of the out integration tests and the behavior of the `echo` command.. Let me know what you think of the test case added.

File: tests/fixtures/bin/docker [hunk 1]
```diff
@@ -1,2 +1,6 @@
 #!/bin/bash
 echo "DOCKER:" "$@"
+
+for var in "$@"; do
+    echo "DOCKER ARG:" "$var"
```
Comment (vito) [inline tests/fixtures/bin/docker]: :+1: makes sense to test it this way

File: tests/out_test.go [hunk 2]
```diff
@@ -55,6 +59,31 @@ var _ = Describe("Out", func() {
...
+						"arg2": "arg with\nnewline",
+						"arg3": "normal",
+					},
+				},
+			})
+
+			Expect(session.Err).To(gbytes.Say(dockerarg(`--build-arg`)))
+			Expect(session.Err).To(gbytes.Say(dockerarg(`arg1=arg with space`)))
+			Expect(session.Err).To(gbytes.Say(dockerarg(`--build-arg`)))
+			Expect(session.Err).To(gbytes.Say(dockerarg(`arg2=arg with\nnewline`)))
```
Comment (vito) [inline tests/out_test.go]: is this correct? since it's a backtick-quoted string, it'll contain literally `"\\n"`, not a linebreak, so this is asserting that it sees `"DOCKER ARG: arg2=arg with\\nnewline"`. Shouldn't that have an actual linebreak, not `\n`?

or does the docker cli interpret that character as a linebreak when parsing the build args?

Comment (jfmyers9) [reply tests/out_test.go]: Good question.

It turns out both:
```
        Expect(session.Err).To(gbytes.Say(dockerarg(`arg2=arg with\nnewline`)))
```
and
```
        Expect(session.Err).To(gbytes.Say(dockerarg(`arg2=arg with
  newline`)))
```
pass the test. From investigating the output, it definitely is receiving the argument with a newline. I wonder if `gbytes.Say` is causing it to behave unexpectedly.

Comment (jfmyers9) [reply tests/out_test.go]: That appears to be the case. When I change the assertion to:
```
       Expect(string(session.Err.Contents())).To(ContainSubstring(dockerarg(`arg2=arg with\nnewline`)))

```
it fails as expected, while the following passes:
```
       Expect(string(session.Err.Contents())).To(ContainSubstring(dockerarg(`arg2=arg with
 newline`)))
```

`gbytes.Say` converts the string to a regex, and `\n` matches the newline character.

Comment (jfmyers9) [reply tests/out_test.go]: That being said, I think the assertion in the test is still correct.

**Comment by vito** [comment]
Ah right, forgot Say does regexes. Makes sense. Thanks for checking!

**Comment by vito** [comment]
Thanks!

**Comment by krishicks** [comment]
I wanted to pass GOOGLE_CREDENTIALS_JSON as a build arg and so also ran into this issue. I pulled this repo, built the image, tried using it, and am seeing:

```
/opt/resource/common.sh: line 47: SKIP_PRIVILEGED: unbound variable
```

**Comment by krishicks** [comment]
The fix for this was to set `privileged: true` in the `resource_type` declaration per a search in Concourse Slack.

**Comment by krishicks** [comment]
Actually, I take that back. It still doesn't work for me; I had to add back the `privileged: true` only because I re-built the image having reverted the commit that adds the SKIP_PRIVILEGED switch.

**Comment by krishicks** [comment]
Added https://github.com/concourse/docker-image-resource/pull/160 to fix the above and added documentation for others.
